apiVersion: apps/v1
kind: Deployment
metadata:
  name: lasntgadmin
  labels:
    app: lasntgadmin
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: lasntgadmin
  template:
    metadata:
      labels:
        app: lasntgadmin
    spec:
      securityContext:
        fsGroup: 33
        #fsGroupChangePolicy: "OnRootMismatch"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: DoesNotExist
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - private-pool
      containers:
      - name: lasntgadmin
        image: php:7-apache
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:    
            path: /
            port: 80
          periodSeconds: 60
          timeoutSeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 60
          timeoutSeconds: 30
        startupProbe:
          #initialDelaySeconds: 60
          httpGet:
            path: /
            port: 80
          periodSeconds: 60
          timeoutSeconds: 30
        envFrom:
          - configMapRef:
              name: lasntgadmin-env
          - secretRef:
              name: lasntgadmin-secret
        resources:
          limits:
            cpu: 200m
            memory: 1024M
          requests:
            cpu: 100m
            memory: 512M
        volumeMounts: 
        - name: wp-content
          mountPath: /var/www/html/wp-content
        - name: wp-config
          mountPath: /var/www/html/wp-config.php
          subPath: wp-config.php
          readOnly: true
        - name: php-config
          mountPath: /usr/local/etc/php/php.ini
          subPath: php.ini
          readOnly: true
      volumes:
        - name: wp-content
          persistentVolumeClaim:
            claimName: lasntgadmin-pvc
        - name: wp-config
          secret: 
            secretName: lasntgadmin-config
        - name: php-config
          configMap:
            name: lasntgadmin-php-config

