apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - pvc.yaml
  - deployment-apache.yaml
  - service-apache.yaml
  - deployment-redis.yaml
  - service-redis.yaml














