apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lasntgadmin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard-rwo"
  resources:
    requests:
      storage: 10Gi
