version: "3.7"

services:

  wordpress:
    build: 
      context: .
      args: 
        - USER_ID=1000
        - WP_LOCALE=en_GB
        - WP_VERSION=latest
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - COMPOSER_AUTOLOAD_FILEPATH=/var/www/html/vendor/autoload.php
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - .:/usr/local/src
      - /var/www/html

  db:
    #cpuset: "0"
    #cpu_quota: 10000
    #mem_limit: 128m
    image: mariadb:10.3
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=secret
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    volumes:
      - /var/lib/mysql
