version: "3.7"

services:

  wp:
    build: 
      context: .
      args: 
        - USER_ID=1000
        - WP_LOCALE=en_GB
        - WP_VERSION=latest
    env_file:
      - .env
    environment:
      - SITE_URL=localhost:8080
      - SITE_TITLE=LASNTG
      - WP_PLUGINS=groups woocommerce mailchimp-for-woocommerce advanced-custom-fields user-role-editor
      - WP_THEME=storefront
      - ADMIN_EMAIL=lasntg@example.com
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=secret
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

  db:
    #cpuset: "0"
    #cpu_quota: 10000
    #mem_limit: 128m
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=secret
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /var/lib/mysql
