version: "3.7"

services:

  apache:
    build: 
      context: .
      dockerfile: httpd.Dockerfile
      args:
        - USER_ID=1000
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    build: 
      context: .
      dockerfile: php.Dockerfile
      args: 
        - USER_ID=1000
        - WP_LOCALE=en_GB
        - WP_VERSION=latest
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - COMPOSER_AUTOLOAD_FILEPATH=/var/www/html/vendor/autoload.php
    depends_on:
      - db
      - redis
    ports:
      - "9000:9000"
    volumes:
      - .:/usr/local/src
      - /var/www/html

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./etc/redis:/usr/local/etc/redis

  db:
    image: mysql:8.4
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
      --skip-log-bin
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=secret
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    volumes:
      - /var/lib/mysql
