version: "3.7"

services:

  wordpress:
    build: 
      context: .
      args: 
        - USER_ID=1000
        - WP_LOCALE=en_GB
        - WP_VERSION=latest
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - .:/usr/local/src
      - /var/www/html
      - ../lasntgadmin-theme:/var/www/html/wp-content/themes/lasntgadmin-theme
      - ../lasntgadmin-plugin_template:/var/www/html/wp-content/plugins/lasntgadmin-plugin_template

  db:
    #cpuset: "0"
    #cpu_quota: 10000
    #mem_limit: 128m
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=secret
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /var/lib/mysql
