version: "3.7"

services:

    wp:
        build: 
            context: .
            args: 
                - USER_ID
                - DB_NAME=wordpress
                - DB_USER=wordpress
                - DB_PASSWORD=secret
                - DB_HOST=db
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html

    db:
        #cpuset: "0"
        #cpu_quota: 10000
        #mem_limit: 128m
        image: mysql:5.7
        environment:
          - MYSQL_DATABASE=wordpress
          - MYSQL_USER=wordpress
          - MYSQL_PASSWORD=secret
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - /var/lib/mysql
