apiVersion: v1
kind: Pod
spec:
  # Use service account that can deploy to all namespaces
  containers:
  - name: cloud-sdk
    image: gcr.io/google.com/cloudsdktool/cloud-sdk
    imagePullPolicy: IfNotPresent
    env:
      - name: CLOUDSDK_COMPUTE_REGION
        value: europe-west1
      - name: CLOUDSDK_CONTAINER_CLUSTER
        value: belgium-01
    command:
      - sleep
    args: 
      - infinity
  - name: docker
    image: docker:20.10.12-alpine3.15
    imagePullPolicy: IfNotPresent
    command:
      - sleep
    args: 
      - infinity
    volumeMounts:
      - name: docker
        mountPath: /var/run/docker.sock # We use the k8s host docker engine
  - name: composer
    image: composer:2
    imagePullPolicy: IfNotPresent
    command:
      - sleep
    args: 
      - infinity
  volumes:
  - name: docker
    hostPath:
      path: /var/run/docker.sock
