- op: replace
  path: /metadata/labels/app
  value: staging-lasntgadmin
- op: replace
  path: /spec/revisionHistoryLimit
  value: 1
- op: replace
  path: /spec/selector/matchLabels/app
  value: staging-lasntgadmin
- op: replace
  path: /spec/template/spec/tolerations
  value: 
  - key: cloud.google.com/gke-nodepool
    operator: Equal
    value: spot-pool
    effect: NoSchedule
- op: remove
  path: /spec/template/spec/containers/0/resources
- op: replace
  path: /spec/template/metadata/labels/app
  value: staging-lasntgadmin
- op: replace
  path: /spec/template/spec/containers/0/image
  value: eu.gcr.io/veri-cluster/lasntgadmin:staging
- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: Always
- op: replace
  path: /spec/template/spec/containers/0/envFrom/0/configMapRef/name
  value: staging-lasntgadmin-env
- op: replace
  path: /spec/template/spec/containers/0/envFrom/1/secretRef/name
  value: staging-lasntgadmin-secret
- op: replace
  path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
  value: staging-lasntgadmin-pvc
- op: replace
  path: /spec/template/spec/volumes/1/secret/secretName
  value: staging-lasntgadmin-wp-config
- op: replace
  path: /spec/template/spec/volumes/2/secret/secretName
  value: staging-lasntgadmin-db-config
- op: replace
  path: /spec/template/spec/volumes/3/configMap/name
  value: staging-lasntgadmin-php-config
- op: replace
  path: /spec/template/spec/volumes/4/configMap/name
  value: staging-lasntgadmin-apache-sites-available-default
- op: replace
  path: /spec/template/spec/volumes/5/configMap/name
  value: staging-lasntgadmin-htaccess-config
- op: replace
  path: /spec/template/spec/volumes/6/configMap/name
  value: staging-lasntgadmin-wordfence-waf
- op: add
  path: /spec/template/spec/containers/0/readinessProbe/httpGet/httpHeaders
  value:
    - name: X-Forwarded-Proto
      value: https
    - name: X-Forwarded-Host
      value: lasntgadmin-staging.veri.ie
    - name: Host
      value: lasntgadmin-staging.veri.ie
    - name: Authorization
      value: Basic bGFzbnRnYWRtaW46dmV4WXdXeDQ4d0NmeVNwYlNnZnlRV0ta
- op: add
  path: /spec/template/spec/containers/0/livenessProbe/httpGet/httpHeaders
  value:
    - name: X-Forwarded-Proto
      value: https
    - name: X-Forwarded-Host
      value: lasntgadmin-staging.veri.ie
    - name: Host
      value: lasntgadmin-staging.veri.ie
    - name: Authorization
      value: Basic bGFzbnRnYWRtaW46dmV4WXdXeDQ4d0NmeVNwYlNnZnlRV0ta
- op: add
  path: /spec/template/spec/containers/0/startupProbe/httpGet/httpHeaders
  value:
    - name: X-Forwarded-Proto
      value: https
    - name: X-Forwarded-Host
      value: lasntgadmin-staging.veri.ie
    - name: Host
      value: lasntgadmin-staging.veri.ie
    - name: Authorization
      value: Basic bGFzbnRnYWRtaW46dmV4WXdXeDQ4d0NmeVNwYlNnZnlRV0ta
