namePrefix: staging-

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../base

patches:
  - path: service-apache.yaml
    target:
      version: v1
      kind: Service
      name: lasntgadmin-service
  - path: deployment-apache.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: lasntgadmin
  - path: ingress.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: lasntgadmin-ingress
  - path: pvc.yaml
    target:
      version: v1
      kind: PersistentVolumeClaim
      name: lasntgadmin-pvc
  - path: deployment-redis.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: lasntgadmin-redis
  - path: service-redis.yaml
    target:
      version: v1
      kind: Service
      name: lasntgadmin-redis-service
