namePrefix: staging-

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: lasntgadmin-env
  literals:
  - ENVIRONMENT=staging
  - SITE_URL=https://lasntgadmin-staging.veri.ie
  - SITE_TITLE=LASNTG
  - WP_PLUGINS=groups woocommerce advanced-custom-fields user-role-editor wp-mail-smtp convergewoocommerce lasntgadmin-grant-funded-payment-gateway
  - WP_THEMES=storefront
  - COMPOSER_AUTOLOAD_FILEPATH=/var/www/html/vendor/autoload.php

bases:
  - ../../base

patchesJson6902:
  - path: service.yaml
    target:
      version: v1
      kind: Service
      name: lasntgadmin-service
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: lasntgadmin
  - path: ingress.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: lasntgadmin-ingress
  - path: pvc.yaml
    target:
      version: v1
      kind: PersistentVolumeClaim
      name: lasntgadmin-pvc
