namePrefix: staging-

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../base

patches:
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: lasntgadmin
  - path: ingress.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: lasntgadmin-ingress
