apiVersion: v1
kind: PersistentVolume
metadata:
  name: lasntgadmin-pv
spec:
  storageClassName: "standard"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: staging-lasntgadmin-pvc
  gcePersistentDisk:
    pdName: gke-belgium-01-f6266c1-pvc-a970268d-8b56-4a79-91ef-6a643befd318
    fsType: ext4
