- op: replace
  path: /spec/template/metadata/labels/app
  value: production-lasntgadmin-redis
- op: replace
  path: /metadata/labels/app
  value: production-lasntgadmin-redis
- op: replace
  path: /spec/selector/matchLabels/app
  value: production-lasntgadmin-redis
- op: replace
  path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/1/values/0
  value: obs-pool
- op: replace
  path: /spec/template/spec/tolerations
  value:
  - key: cloud.google.com/gke-nodepool
    operator: Equal
    value: obs-pool
    effect: NoSchedule
- op: replace 
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      cpu: 500m
      memory: 1024M
    requests:
      cpu: 250m
      memory: 512M
- op: replace
  path: /spec/template/metadata/labels/app
  value: production-lasntgadmin-redis
  path: /spec/template/spec/volumes/0/configMap/name
  value: production-lasntgadmin-redis-config
