namePrefix: production-

generatorOptions:
  disableNameSuffixHash: true

bases:
  - ../../base

patchesJson6902:
  - path: service.yaml
    target:
      version: v1
      kind: Service
      name: lasntg-service
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: lasntg
  - path: ingress.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: lasntg-ingress
  - path: pvc.yaml
    target:
      version: v1
      kind: PersistentVolumeClaim
      name: lasntg-pvc

