namePrefix: production-

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: lasntgadmin-config
    files: 
      - wp-config.php
  - name: lasntgadmin-secret
    env: secrets.txt

