namePrefix: staging-

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: lasntgadmin-wp-config
    files: 
      - wp-config.php
  - name: lasntgadmin-db-config
    files: 
      - db-config.php
  - name: lasntgadmin-secret
    env: secrets.txt

